### ISSUE TITLE
Not working on fedora 38

### ISSUE THREAD

**Issue by janTatesa** [eeeXun/gtt#19]
I installed first alsa-lib-devel, then golang-bin, then ran go install github.com/eeeXun/gtt@latest then ran gtt and it says command not found

**Comment by eeeXun** [comment]
Did you add `$HOME/go/bin` to your `$PATH`?

```
export PATH=$PATH:$HOME/go/bin
```

**Comment by janTatesa** [comment]
> Did you add `$HOME/go/bin` to your `$PATH`?
> 
> ```
> export PATH=$PATH:$HOME/go/bin
> ```

Thanks
