### ISSUE TITLE
[Feat] Ability to specify left and right language on startup

### ISSUE THREAD

**Issue by Dimfred** [eeeXun/gtt#2]
Hey great tool!
It would be great to have the ability to specify the languages (--left-lang, --right lang) directly on startup. This way one could alias common languages to have them available faster

**Comment by Dimfred** [comment]
Ouh I just saw that you store a config file. It would also be fine for me for example to allow specifying the config path that would be essentially the same.

**Comment by eeeXun** [comment]
GTT looking for `$XDG_CONFIG_HOME` first. If you already set this environment variable , then config file would place under `$XDG_CONFIG_HOME/gtt/`.
Otherwise, it would place under `$HOME/.config/gtt/`.

So maybe you can write 
```sh
export XDG_CONFIG_HOME=xxx
```
in `~/.profile`, `~/.bashrc` or `~/.zshrc`

**Comment by Dimfred** [comment]
Yeah I mean it's kind of a hack. I know am just opening the config file before calling gtt and modify the yaml to my needs, which also works, some cli parameters would be simpler imo. But your call.

**Comment by eeeXun** [comment]
> some cli parameters would be simpler imo

Sorry, I can't get your point. Could you give me an example?

**Comment by Dimfred** [comment]
Okay so I would like to have is e.g.:
`gtt --src English --dest German`
currently this is not really possible.
Like you suggest you could do something like

```
config1 = ~/.config/gtt/config1/gtt/config.yaml # this has src:English dst: German 
config2 = ~/.config/gtt/config2/gtt/config.yaml # this has src:English dst:Russian
```

Now you can:

```
XDG_CONFIG_HOME=~/.config/gtt/config1 gtt
XDG_CONFIG_HOME=~/.config/gtt/config2 gtt
```

I just think it's inconvenient. So what would be good is directly override `--src / --dest`
Or call gtt with `gtt -c /path/to/config`

**Comment by eeeXun** [comment]
Okay, I understand. I'll add `--src / --dest` to allow user to pass in parameters.
But for multi-config file. I don't think it get much benefit on this project.

**Comment by Dimfred** [comment]
Yeah sure. I think the `--src / --dest` would suffice. Multi config could be simpler for you since then it's only one param. But I think `--src / --dest` makes more sense.

**Comment by eeeXun** [comment]
Close via https://github.com/eeeXun/GTT/commit/da5fc2225862bc6d311e16de916e73d3c4eea627

**Comment by Dimfred** [comment]
Awesome thx!
