### ISSUE TITLE
add custom keybindings support

### ISSUE THREAD

**Issue by doums** [eeeXun/gtt#21]
Hi!
First really handy and nice made tool, thx for it ;)
As a suggestion, it could be very cool to add custom keybindings support.

**Comment by eeeXun** [comment]
There are many keys that conflicts with the TUI framework. Like `C-a` begin of line, `C-e` end of line, etc. And `alt` is not work on macOS mention in https://github.com/eeeXun/gtt/pull/1#issuecomment-1290449401.

My current solution for this is like [customize theme](https://github.com/eeeXun/gtt/blob/master/example/theme.yaml). User can modify the yaml file, like translation key mapping to `A-j` if you are not in macOS. But user must be aware of any conflict with TUI framework or your system. How do you think?

**Comment by doums** [comment]
Hi, I think when you parse the config file you should be able to check for any key conflicts programmatically between user custom keys override and the TUI framework keys? And so notify the user on app startup?

I'm not a go dev, so I dont know the TUI framework you used to build this tool. But for a TUI framework, allowing the user to define its own keybindings for program actions is generally a first class feature.

> My current solution for this is like [customize theme](https://github.com/eeeXun/gtt/blob/master/example/theme.yaml). User can modify the yaml file, like translation key mapping to A-j if you are not in macOS. But user must be aware of any conflict with TUI framework or your system. How do you think?

Yes that the way to go, inside the config file, having a `keys` section where the user can map "key to action" as he sees fit.
And adding a section in the readme `key mapping` is a must have.

(Im not a mac user, but if there are constrains with mac well just add it in the doc to let users know, but dont block the feature because on mac "it's more complicated").

**Comment by eeeXun** [comment]
Thanks for your feedback. I'll manage to do that.

**Comment by doums** [comment]
Okay cool! Thx again for your work, it's already an amazing tool.

**Comment by eeeXun** [comment]
I've implemented in #22, you could checkout [custom-key](https://github.com/eeeXun/gtt/tree/custom-key) branch.

>This is the [config file](https://github.com/eeeXun/gtt/blob/custom-key/example/keymap.yaml)
>
>For key to combine with `Ctrl`, value can be `" "` (Space), `"\\"` or `'\'` (backslash), `"]"`, `"^"`, `"_"`, `"a"` to `"z"` (lower case).
>
>Or the function key, value can be `"F1"` to `"F64"`
>
>⚠️ Note, don't use `"c"`, `<C-c>` is for exit program

From the above, is there any part that may mislead the user?

If it is ok, I'm going to merge it

**Comment by eeeXun** [comment]
Done in #22
