### ISSUE TITLE
Added gtt to nixpkgs

### ISSUE THREAD

**Issue by linuxissuper** [eeeXun/gtt#26]
Hi,  

thanks for the project :)    
just wanted to let you know, that gtt is now in nixpkgs unstable  
  
https://github.com/NixOS/nixpkgs/pull/282706

**Comment by eeeXun** [comment]
Wow, that's awesome. As I'm not familiar with Nix. Could you help me write the installation guide below [Arch Linux (AUR)](https://github.com/eeeXun/gtt?tab=readme-ov-file#arch-linux-aur) in README. Thanks in advance.
