### ISSUE TITLE
Missing package alsa during install

### ISSUE THREAD

**Issue by maxmahlke** [eeeXun/gtt#3]
I'm not familiar with `go`: I cloned the repository using `git clone` and ran `go install` in the root directory. I get the following message

```
# pkg-config --cflags  -- alsa
Package alsa was not found in the pkg-config search path.
Perhaps you should add the directory containing `alsa.pc'
to the PKG_CONFIG_PATH environment variable
No package 'alsa' found
pkg-config: exit status 1
```

I tried the following commands to resolve this without success:

```
go install alsa  # failed: package alsa is not in GOROOT
go install https://github.com/yobert/alsa  # succeeded but did not resolve the issue
```

Could you tell me how to install the dependency? A bunch of other dependencies were downloaded upon running the initial `go install` command, so `alsa` might be missing from the requirements file.

**Comment by eeeXun** [comment]
What's the output of `go version`?
Did you test with `go get`?

**Comment by maxmahlke** [comment]
```
$ go version
go version go1.18.1 linux/amd64
```

and running `go get` in the GTT root directory gives

```
$ go get
go: downloading gopkg.in/yaml.v2 v2.4.0
```

Running `go install` afterwards gives the same error message about the missing `alsa` package.

**Comment by eeeXun** [comment]
What's the out put of `go build` after `go get`?

**Comment by maxmahlke** [comment]
Same error message as for `go install`. Is https://github.com/yobert/alsa the package that I have to install?

**Comment by eeeXun** [comment]
Are you using Ubuntu? If so, can you try to install `libasound2-dev`?

**Comment by maxmahlke** [comment]
Yes, running 

```
sudo apt install libasound2-dev
```

fixed the issue. Thanks!

Now I have a new issue, no translation is shown. I'll open a new issue for that.
